name: Build, Test and Release a Beta version

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./AzureFunctions.EventGrid/AzureFunctions.EventGrid.csproj
    - name: Build
      run: dotnet build ./AzureFunctions.EventGrid/AzureFunctions.EventGrid.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test ./AzureFunctions.EventGrid/AzureFunctions.EventGrid.csproj --no-restore --verbosity normal
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        prerelease: true
    
